config/routes.rb
Rails.application.routes.draw do
  resources :packages
  resources :users

   root 'packages#index'

end

app/models/package.rb
class Package < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
	def index
		@packages = Package.all
	end

	def show
		@package = Package.find(params[:id])
	end

	def new
		@package = Package.new
	end

	def create
		@package = Package.new(package_params)
			if @package.save
				redirect_to(root_path)
			else
				render :new
			end
	end

	def edit
		@package = Package.find(params[:id])
	end

	def update
		@package = Package.find(params[:id])
			if @package.update(package_params)
				redirect_to(@package)
			else
				render :edit
			end
	end

	def destroy
		@package = Package.find(params[:id])
		@package.destroy
		redirect_to(root_path)
	end

	private

	def package_params
		params.require(:package).permit(:title, :description, :image)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path, notice:"Thanks for signing up!"
		else
		render :new
		end	
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
			if @user.save
				redirect_to @user, notice:"Account details updated!"
			else
				render :edit
			end
	end

private

def user_params
	params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
  <nav class="navbar">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to("Marketplace", root_path)%></li>
        <li><%= link_to("My Packages", "#")%></li>
      </ul>

    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thinkworth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<div class ="container">
<%= yield %>
</div>

</body>
</html>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name, autofocus:true %><br>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %><br>

	<%= f.label :username %>
	<%= f.text_field :username %><br>

	<%= f.label :email %>
	<%= f.email_field :email %><br>

	<%= f.label :password %>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %><br>

	<%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1> edit </h1>

<%= render 'user_form' %>

<%= link_to("Cancel", @user)%>

app/views/users/index.html.erb
<h2>Users</h2>

<%= link_to("Sign up",new_user_path)%><br><br>



<table class="bordered striped">
  	
	<thead>
		<tr>
        	<th>User</th>
        	<th>First Name</th>
        	<th>Last Name</th>
        	<th>Email</th>
        </tr>
    </thead>

    <tbody>
    	<% @users.each do |u| %>	
       	<tr>
        	<td><strong><%= link_to(u.username, u) %></strong></td>
        	<td><%= u.first_name %></td>
        	<td><%= u.last_name %></td>
        	<td><%= u.email %></td>
        </tr>
        <% end %> 
    </tbody>
</table>	

app/views/users/new.html.erb
<h2>Create New User</h2>

<%= render 'user_form' %>

<%= link_to("Cancel", users_path)%>

app/views/users/show.html.erb
<h2> <%= @user.username %>'s Page </h2>

<p>
	<strong>Full Name: </strong><%= @user.first_name%> <%= @user.last_name%>
</p>

<p>
	<strong>Email Address: </strong><%= @user.email%> 
</p>

<small>
<p>
	<strong>Join Date: </strong>
	<%= @user.created_at %> 
</p>
</small>
<%= link_to("Back", users_path)%> |
<%= link_to("Edit", edit_user_path(@user))%> |
<%= link_to("Delete", user_path, method: :delete,
			data:{confirm:("Are you sure you want to delete this user?")}) %>